# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - AzureGoNugetApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_7249a535ea7d481da8a22fed62982a24 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bc8aa02f10dc46faa5da97f0d10c6cd4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7249a535ea7d481da8a22fed62982a24 }}/zzfima/docker-website-golang-nuget-info:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AzureGoNugetApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_345b23479e9d4585b1cb1b2d88d77e57 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7249a535ea7d481da8a22fed62982a24 }}/zzfima/docker-website-golang-nuget-info:${{ github.sha }}'